sudo: false

language: php
php:
  - '8.0'
  - '8.1'
  - '8.2'
  - '8.3'
  - 'nightly'

allow_failures:
  - php: nightly

cache:
  directories:
    - ext/argon2

notifications:
  email:
    on_success: change
    on_failure: change

script:
  - cd ext/argon2 && CFLAGS="-fPIC" make -j1 OPTTARGET=i686 && make test && rm libargon2.so.1 && cd ../..
  - phpize
  - ./configure --with-argon2
  - NO_INTERACTION=true make test